vim.keymap.set('n', '<leader>1', function()
  require('config.utils.terminals').run('cargo build --release ; time cargo run --release', { direction = 'float' })
end, { desc = 'Run Rust Proj', buffer = true })
vim.keymap.set('n', '<leader>2', function()
  require('config.utils.terminals').run('time cargo test', { direction = 'float' })
end, { desc = 'Run Rust Proj', buffer = true })
vim.keymap.set('n', '<leader>lt', function()
  require('config.utils.terminals').run('time cargo test')
end, { desc = 'LSP Test' })
